#:import C kivy.utils.get_color_from_hex

<ManagementScreen@Screen>:
    name: 'management'
    FloatLayout:
        MDLabel:
            text: 'Management Page'
            halign: 'center'
            pos_hint: {'center_x': .5,'center_y': 0.5}
        
        MDFlatButton:
            text: 'BACK'
            md_bg_color: '#FFFF00'
            pos_hint: {'center_x': .5,'center_y': 0.4}
            on_release: app.root.current = 'home'